name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build'
        type: boolean
        required: true
        default: false
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/prokleta-kuja/ciklonalozi:latest
      #       ghcr.io/prokleta-kuja/ciklonalozi:${{ github.run_number }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Production
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."