name: Build & Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/prokleta-kuja/ciklonalozi:latest
            ghcr.io/prokleta-kuja/ciklonalozi:${{ github.run_number }}