name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'push' || github.event.inputs.build }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1 
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/prokleta-kuja/ciklonalozi:latest
      #       ghcr.io/prokleta-kuja/ciklonalozi:${{ github.run_number }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Prepare SSH
        env:
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo $remote_key > ~/.ssh/id_rsa
          hosts="$(dig +short "$remote_host" | grep -v '\.$' | sed -z 's|\n|,|g')$remote_host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - name: Run remotely
        run: ssh -p $remote_port $remote_user@$remote_host "pwd; ls -hal"